import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>SEA-CT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
        <meta name="viewport" content="width=device-width, user-scalable=no"></meta>
      </Head>
      <Component {...pageProps} />
    </>
  )
}
